"""Run one ComfyUI workflow through PanelForge's minimal HTTP client."""

from __future__ import annotations

import argparse
import json
import sys
import time
from pathlib import Path
from typing import Any
from urllib.error import HTTPError, URLError
from uuid import uuid4


PROJECT_ROOT = Path(__file__).resolve().parents[1]
SRC_ROOT = PROJECT_ROOT / "src"
sys.path.insert(0, str(SRC_ROOT))

from panelforge.infrastructure.comfy import ComfyHttpClient


PNG_SIGNATURE = b"\x89PNG\r\n\x1a\n"


def load_workflow(path: Path) -> dict[str, Any]:
    with path.open(encoding="utf-8") as workflow_file:
        workflow = json.load(workflow_file)

    if not isinstance(workflow, dict) or not workflow:
        raise ValueError("workflow must be a non-empty JSON object")
    return workflow


def wait_for_history(
    client: ComfyHttpClient,
    prompt_id: str,
    *,
    run_timeout: float,
    poll_interval: float,
) -> dict[str, Any]:
    if run_timeout <= 0:
        raise ValueError("run_timeout must be greater than zero")
    if poll_interval <= 0:
        raise ValueError("poll_interval must be greater than zero")

    deadline = time.monotonic() + run_timeout
    while True:
        history = client.get_history(prompt_id)
        run = history.get(prompt_id)
        if isinstance(run, dict):
            status = run.get("status")
            if (
                isinstance(status, dict)
                and status.get("status_str") == "success"
                and status.get("completed") is True
            ):
                return run
            raise RuntimeError(f"ComfyUI execution did not succeed: {status}")

        remaining = deadline - time.monotonic()
        if remaining <= 0:
            raise TimeoutError(
                f"ComfyUI did not complete prompt {prompt_id!r} "
                f"within {run_timeout:g} seconds"
            )
        time.sleep(min(poll_interval, remaining))


def find_first_image(run: dict[str, Any]) -> tuple[str, dict[str, str]]:
    outputs = run.get("outputs")
    if not isinstance(outputs, dict):
        raise ValueError("ComfyUI history does not contain an outputs object")

    for node_id, node_output in outputs.items():
        if not isinstance(node_output, dict):
            continue
        images = node_output.get("images")
        if not isinstance(images, list):
            continue
        for image in images:
            if not isinstance(image, dict):
                continue

            filename = image.get("filename")
            subfolder = image.get("subfolder", "")
            folder_type = image.get("type", "output")
            if (
                isinstance(filename, str)
                and filename
                and isinstance(subfolder, str)
                and isinstance(folder_type, str)
            ):
                return str(node_id), {
                    "filename": filename,
                    "subfolder": subfolder,
                    "type": folder_type,
                }

    raise ValueError("ComfyUI history does not contain an image output")


def validate_png(content: bytes) -> None:
    if not content.startswith(PNG_SIGNATURE):
        raise ValueError("downloaded output is not a PNG image")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Submit a ComfyUI API workflow and download its first image."
    )
    parser.add_argument("workflow", type=Path, help="Path to workflow_api.json")
    parser.add_argument(
        "--base-url",
        default="http://127.0.0.1:8188",
        help="ComfyUI base URL (default: %(default)s)",
    )
    parser.add_argument(
        "--client-id",
        default=None,
        help="Stable ComfyUI client ID (a smoke-test ID is generated by default)",
    )
    parser.add_argument(
        "--http-timeout",
        type=float,
        default=30.0,
        help="Timeout for each HTTP call in seconds (default: %(default)s)",
    )
    parser.add_argument(
        "--run-timeout",
        type=float,
        default=600.0,
        help="Maximum generation time in seconds (default: %(default)s)",
    )
    parser.add_argument(
        "--poll-interval",
        type=float,
        default=1.0,
        help="History polling interval in seconds (default: %(default)s)",
    )
    return parser.parse_args()


def run_smoke(args: argparse.Namespace) -> int:
    workflow = load_workflow(args.workflow)
    client_id = args.client_id or f"panelforge-smoke-{uuid4()}"
    client = ComfyHttpClient(
        args.base_url,
        client_id=client_id,
        timeout=args.http_timeout,
    )

    print(f"Submitting {args.workflow} to {client.base_url}", flush=True)
    prompt_id = client.submit_workflow(workflow)
    print(f"Queued prompt_id={prompt_id}", flush=True)

    run = wait_for_history(
        client,
        prompt_id,
        run_timeout=args.run_timeout,
        poll_interval=args.poll_interval,
    )
    node_id, image = find_first_image(run)
    content = client.download_output(
        filename=image["filename"],
        subfolder=image["subfolder"],
        folder_type=image["type"],
    )

    validate_png(content)

    print(
        f"Downloaded node={node_id} filename={image['filename']!r} "
        f"bytes={len(content)} format=PNG",
        flush=True,
    )
    return 0


def main() -> int:
    args = parse_args()
    try:
        return run_smoke(args)
    except HTTPError as error:
        body = error.read().decode("utf-8", errors="replace")
        print(
            f"ComfyUI returned HTTP {error.code} for {error.geturl()}",
            file=sys.stderr,
        )
        if body:
            print(body, file=sys.stderr)
        return 1
    except URLError as error:
        print(
            f"Cannot reach ComfyUI at {args.base_url}: {error.reason}",
            file=sys.stderr,
        )
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
